import './globals.css'
import Header from  "./components/layout/Header"



export const metadata = {
  title: 'Panaverse Dao',
  description: 'Generated by Rohan Ali',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      {/* Header */}
      <Header />
        {children}</body>
      
    </html>
  )
}
